displayName=Fog of War
author=Dazuz
description=Applies a fog of war effect outside the player render distance, in both the world and on the minimap.
tags=fog of war,fow,fog,war,render distance,render,draw,draw distance
version=2026-05-23
build=standard
plugins=com.fogofwar.FogOfWarPlugin
